### ISSUE TITLE
Many functions do not work on web

### ISSUE THREAD

**Issue by Iumen** [sugarlabs/sugarlabs-calculate#54]
When I go to https://try.sugarizer.org/, the add() function works but mul() does not work. It gives "undefined symbol mul". I have installed the sugar desktop environment in ubuntu and it works correctly.

**Comment by quozl** [comment]
Thanks.  Different source code is used for the Calculate activity on Sugarizer, and this repository is for the Sugar desktop activity instead.  Please raise the issue at https://github.com/llaske/sugarizer/issues
